[package]
name = "german_dictionary"
version = "0.1.0"
edition = "2021"

[dependencies]
lingua = "1.5.0"
reqwest = "0.11.22"
serde = "1.0.189"
serde_json = "1.0.107"
tokio = {version= "1.33.0", features = ["full"]}
